language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - export PATH="$PATH:./flutter/bin"
  - cd example
  - flutter pub get
cache:
  directories:
    - $HOME/.pub-cache
