name: build
on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - master

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
         java-version: '12.x'
     - run: git clone https://github.com/flutter/flutter.git
     - run: echo "::add-path::/flutter/bin"
     - run: cd example
     - run: flutter build apk
