name: build
on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - master

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
      - name: go to example
        run: cd example
      - name: Install Dependencies
        run: flutter packages get
      - name: Format
        run: flutter format --set-exit-if-changed lib test
      - name: Analyze
        run: flutter analyze lib test
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
