name: build
on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - master
env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*hover_ussd*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*hover_ussd_example*"

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/build-example.sh android
