name: build
on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - master
env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*hover_ussd*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*hover_ussd_example*"

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-java@v1
       with:
         java-version: '12.x'
     - run: git clone https://github.com/flutter/flutter.git
     - run: export PATH="$PATH:`pwd`/flutter/bin"
     - run: cd example
     - run: flutter build apk
